import type { AppProps } from "next/app";
// import Head from "next/head";
import GlobalStyles from "@/styles/GlobalStyles";
import AbortController from "abort-controller";
import fetch, { Headers, Request, Response } from "node-fetch";

import { wrapper } from "../store";
import "tailwindcss/tailwind.css";

Object.assign(globalThis, {
  fetch,
  Headers,
  Request,
  Response,
  AbortController,
});

const _App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      {/* <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <GlobalStyles />
      <Component {...pageProps} />;
    </>
  );
};

export default wrapper.withRedux(_App);
